<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-05 at 18:40:56.
 */
class gameControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var gameController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new gameController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers gameController::viewAction
     * @todo   Implement testViewAction().
     */
    public function testViewAction() {
        // Remove the following lines when you implement this test.
        $this->object->viewAction();
    }

    /**
     * @covers gameController::checkTaskAction
     * @todo   Implement testCheckTaskAction().
     */
    public function testCheckTaskAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gameController::cancelTaskAction
     * @todo   Implement testCancelTaskAction().
     */
    public function testCancelTaskAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gameController::finishAction
     * @todo   Implement testFinishAction().
     */
    public function testFinishAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers gameController::goAction
     * @todo   Implement testGoAction().
     */
    public function testGoAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
