<?php

require "models/adminModel.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-09 at 11:19:13.
 */
class adminModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var adminModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new adminModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers adminModel::resetTestData
     * @todo   Implement testResetTestData().
     */
    public function testResetTestData() {
        // Remove the following lines when you implement this test.
        $this->object->resetTestData();
    }

    /**
     * @covers adminModel::execSQL
     * @todo   Implement testExecSQL().
     */
    public function testExecSQL() {
        // Remove the following lines when you implement this test.
        //$this->object->execSQL("\sqlBase\dozor.sql");
    }

}
