<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-05 at 18:17:57.
 */
class profileModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var profileModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new profileModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers profileModel::loadTeam
     * @todo   Implement testLoadTeam().
     */
    public function testLoadTeam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers profileModel::loadGames
     * @todo   Implement testLoadGames().
     */
    public function testLoadGames() {
        // Remove the following lines when you implement this test.
        $this->object->loadGames();
    }

}
