<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-03 at 22:51:47.
 */

require_once '/models/registermodel.php';

class registerModelTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var registerModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new registerModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers registerModel::loadData
     * @todo   Implement testLoadData().
     */
    public function testLoadData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers registerModel::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers registerModel::loadPass
     * @todo   Implement testLoadPass().
     */
    public function testLoadPass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers registerModel::loadEmail
     * @todo   Implement testLoadEmail().
     */
    public function testLoadEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers registerModel::writeData
     * @todo   Implement testWriteData().
     */
    public function testWriteData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers registerModel::isTeamCreated
     * @todo   Implement testIsTeamCreated().
     */
    public function testIsTeamCreated()
    {
        // Remove the following lines when you implement this test.
        $this->object->loadData(Array('name' => 'luchnck'));
        $this->assertTrue($this->object->isTeamCreated());
        
        $this->object->loadData(Array('name' => 'vasyapu'));
        $this->assertFalse($this->object->isTeamCreated());
    }
}
