<?php

require_once '/bootstrap.php';
require_once '/helpers/validator.php';

echo ini_get('include_path');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-24 at 22:34:24.
 */
class validatorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var validator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $params = Array(
                'match' =>  Array(
                                'name'  => Array(
                                              'type' => 'string',
                                              'options' => Array(
                                                    'format' => VALIDATE_NUM . VALIDATE_ALPHA,
                                                    'min_length' => 6,
                                                  )
                                          ),
                                'id'    => Array(
                                              'type' => 'number',
                                              'options' => Array(),
                                          ),
                                'email' => Array(
                                              'type' => 'email',
                                              'options' => Array(
                                                    'check_domain' => 'false',
                                                    'fullTLDValidation' => 'false',
                                                    'use_rfc822' => 'false',
                                                    'VALIDATE_GTLD_EMAILS' => 'true',
                                                    'VALIDATE_CCTLD_EMAILS' => 'true',
                                                    'VALIDATE_ITLD_EMAILS' => 'true',
                                                    ),
                                          ),
                                'pass'  => Array(
                                              'type' => 'string',
                                              'options' => Array(
                                                    'format' => VALIDATE_NUM . VALIDATE_ALPHA . VALIDATE_PUNCTUATION,
                                                    'min_length' => 6,
                                                  ),
                                          )
                                ),
            
                'notEmpty' =>Array('name','pass','email'),
            
                'equals' => Array(
                                  'pass' => '123456!;',
                                ),
                );
        
        $this->object = new validator($params);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers validator::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        /*login*/
       $this->assertTrue($this->object->validate('name','georgy12345'));
       $this->assertFalse($this->object->validate('name','georgy!12345'));
       $this->assertFalse($this->object->validate('name','Жора'));
       
       /*pass*/
       $this->assertTrue($this->object->validate('pass','123456!;'));
       $this->assertFalse($this->object->validate('pass','1234'));
       $this->assertFalse($this->object->validate('pass','1234'));
       
       /*Проверка требует публичного дескриптора*/
       $this->assertFalse($this->object->checkNotEmpty('pass',''));
       
       /*email*/
       $this->assertTrue($this->object->validate('email','maxon@overwrite.com'));
       $this->assertFalse($this->object->validate('email','luchnckyandex.ru'));
       $this->assertFalse($this->object->validate('email',''));
       $this->assertFalse($this->object->validate('email','михаил@yandex.ru'));
       $this->assertFalse($this->object->validate('email','luchnckyandex'));
       $this->assertFalse($this->object->validate('email','$.("#hello").setParams();luchnck@yandex.ru'));
       
    }
}
